version: '3.3'

services:
  php-fpm-api:
    build: ./ropi-api/
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www/html
    command: sh -c "/var/www/html/ropi-api/entrypoint.sh"
    tty: true
  php-fpm-frontend:
    build: ./ropi-frontend/
    ports:
      - 3000:3000
    volumes:
      - ./:/var/www/html
    command: sh -c "/var/www/html/ropi-frontend/entrypoint.sh"
    tty: true
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ropipass
      MYSQL_DATABASE: dbropi
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
