version: '3.3'

services:
  php-fpm:
    build: ./
    ports:
      - 80:8000
    volumes:
      - ./:/var/www/html
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: passropi
      MYSQL_DATABASE: db_database
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql