version: '3.3'

services:
  php-fpm-ropi-api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./..:/var/www/html

  mariadb-ropi-api:
    image: mariadb
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ropipass
      MYSQL_DATABASE: dbropi

  phpmyadmin-ropi-api:
    depends_on:
      - mariadb-ropi-api
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST:  mariadb-ropi-api
